# Project information
site_name: Semaphore 2.0 documentation
site_description: Semaphore 2.0 documentation
site_author: Rendered Text
site_url: https://docs.semaphoreci.com

# Repository
repo_name: semaphoreci/docs
repo_url: https://github.com/semaphoreci/docs

# Copyright
copyright: '&copy; 2009-2019 Rendered Text'

theme:
  name: 'material'
  logo: 'images/logo-white.png'
  favicon: 'images/favicon.ico'
  feature:
    tabs: false
  palette:
    primary: 'green'
    accent: 'green'
extra:
  social:
    - type: 'github'
      link: 'https://github.com/semaphoreci'
    - type: 'twitter'
      link: 'https://twitter.com/semaphoreci'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/company/rendered-text'
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: '&#128279;'
nav:
  - Welcome: index.md
  - Guided Tour:
    - Getting Started: guided-tour/getting-started.md
    - Creating your first project: guided-tour/creating-first-project.md
    - Concepts: guided-tour/concepts.md
    - Customizing Your Pipeline: guided-tour/customize-pipeline.md
    - Customizing the Build Environment: guided-tour/customize-build-env.md
    - Using Databases and Services: guided-tour/using-database-and-services.md
    - Caching Dependencies: guided-tour/caching-dependencies.md
    - Environment Variables and Secrets: guided-tour/environment-variables-and-secrets.md
    - Deploying With Promotions: guided-tour/deploying-with-promotions.md
    - Migration guide for Semaphore Classic users: guided-tour/migration-guide.md
    - Slack Notifications: guided-tour/slack-notifications.md
  - Use Cases:
    - Tutorials and Example Projects: use-cases/tutorials-and-examples.md
    - Debugging with SSH Access: use-cases/debugging-with-ssh.md
    - Download and cache a custom file: use-cases/download-and-cache-a-custom-file.md
    - Build matrix: use-cases/build-matrix.md
    - Modeling complex workflows: use-cases/modeling-complex-workflows.md
    - Working with Docker: use-cases/working-with-docker.md
    - Publishing Docker images on DockerHub: use-cases/publishing-docker-images-on-dockerhub.md
    - Pushing Docker images to AWS Elastic Container Registry (ECR): use-cases/pushing-docker-images-to-aws-elastic-container-registry-ecr.md
    - Pushing Docker images to Google Container Registry (GCR): use-cases/pushing-docker-images-to-google-container-registry-gcr.md
    - Docker layer caching: use-cases/docker-layer-caching.md
    - Using Docker Compose in CI: use-cases/using-docker-compose-in-ci.md
    - CI/CD for Microservices on Kubernetes: use-cases/ci-cd-for-microservices-on-kubernetes.md
    - Code Signing for iOS projects: use-cases/code-signing-for-ios-projects.md
    - Django Continuous Integration: use-cases/django-continuous-integration.md
    - Elixir Phoenix Continuous Integration: use-cases/elixir-phoenix-continuous-integration.md
    - Golang Continuous Integration: use-cases/golang-continuous-integration.md
    - iOS Continuous Integration with Xcode: use-cases/ios-continuous-integration-with-xcode.md
    - Java Spring Continuous Integration: use-cases/java-spring-continuous-integration.md
    - Node.js and TypeScript Continuous Integration: use-cases/node-js-and-typescript-continuous-integration.md
    - Laravel PHP Continuous Integration: use-cases/laravel-php-continuous-integration.md
    - Rails Continuous Integration: use-cases/rails-continuous-integration.md
    - Scala Play Continuous Integration: use-cases/scala-play-continuous-integration.md
    - Continuous Deployment of a Static Website: use-cases/continuous-deployment-of-a-static-website.md
    - Google Cloud Run Continuous Deployment: use-cases/google-cloud-run-continuous-deployment.md
    - Netlify Continuous Deployment: use-cases/netlify-continuous-deployment.md
    - Heroku Deployment: use-cases/heroku-deployment.md
    - Zeit Now Continuous Deployment: use-cases/zeit-now-continuous-deployment.md
    - Deployment Dashboards: use-cases/deployment-dashboards.md
    - Using Private Dependencies: use-cases/using-private-dependencies.md
    - TestFlight iOS app distribution: use-cases/testflight-ios-app-distribution.md
    - HockeyApp iOS app distribution: use-cases/hockeyapp-ios-app-distribution.md
    - Clojure Luminus CI/CD: use-cases/clojure-luminus-ci-cd.md
    - Skip building some commits with [ci skip]: use-cases/skip-building-some-commits-with-ci-skip.md
    - Configuring parallel tests with Code Climate: use-cases/configuring-parallel-tests-with-code-climate.md
    - Deployment to AWS Elastic Beanstalk: use-cases/deployment-to-aws-elastic-beanstalk.md
    - "Fail-Fast: Stop running tests on the first failure": use-cases/fail-fast-stop-running-tests-on-the-first-failure.md
    - Project workflow trigger options: use-cases/project-workflow-trigger-options.md
    - Auto-cancel previous pipelines on a new push: use-cases/auto-cancel-previous-pipelines-on-a-new-push.md
    - Artifacts: use-cases/artifacts.md
  - Programming Languages:
    - C: programming-languages/c.md
    - C++: programming-languages/cpp.md
    - Clojure: programming-languages/clojure.md
    - Elixir: programming-languages/elixir.md
    - Erlang: programming-languages/erlang.md
    - Go: programming-languages/go.md
    - Java: programming-languages/java.md
    - JavaScript and Node.js: programming-languages/javascript-and-node-js.md
    - PHP: programming-languages/php.md
    - Python: programming-languages/python.md
    - Ruby: programming-languages/ruby.md
    - Rust: programming-languages/rust.md
    - Scala: programming-languages/scala.md
    - Swift: programming-languages/swift.md
  - CI/CD Environment:
    - Machine Types: ci-cd-environment/machine-types.md
    - Ubuntu 18.04 image: ci-cd-environment/ubuntu-18.04-image.md
    - macOS Mojave Image: ci-cd-environment/macos-mojave-image.md
    - Custom CI/CD environment with Docker: ci-cd-environment/custom-ci-cd-environment-with-docker.md
    - Toolbox Reference: ci-cd-environment/toolbox-reference.md
    - Environment Variables: ci-cd-environment/environment-variables.md
    - "sem-version: Managing language versions on Linux": ci-cd-environment/sem-version-managing-language-versions-on-linux.md
    - "sem-service: Managing databases and services on Linux": ci-cd-environment/sem-service-managing-databases-and-services-on-linux.md
    - Configuring Database Access: ci-cd-environment/configuring-database-access.md
    - Caching Dependencies and Directories: ci-cd-environment/caching-dependencies-and-directories.md
    - Artifact CLI reference: ci-cd-environment/artifact-cli-reference.md
  - Reference:
    - sem command line tool: reference/sem-command-line-tool.md
    - Pipeline YAML Reference: reference/pipeline-yaml-reference.md
    - Secrets YAML reference: reference/secrets-yaml-reference.md
    - Projects YAML reference: reference/projects-yaml-reference.md
    - Dashboards YAML reference: reference/dashboards-yaml-reference.md
    - Jobs YAML Reference: reference/jobs-yaml-reference.md
    - Notifications YAML Reference: reference/notifications-yaml-reference.md
    - Slack Notifications: reference/slack-notifications.md
    - Semaphore Changelog: reference/semaphore-changelog.md
    - Quotas and Limits: reference/quotas-and-limits.md
    - Conditions Reference: reference/conditions-reference.md
  - Account Management:
    - Billing: account-management/billing.md
    - User Management and Permissions: account-management/user-management-and-permissions.md
    - Checking the connection between GitHub and Semaphore 2.0: account-management/checking-the-connection-between-github-and-semaphore-2.0.md
    - Discounts: account-management/discounts.md
    - Working with GitHub SSO: account-management/working-with-github-sso.md
