# Project information
site_name: Semaphore 2.0 Documentation
site_description: Semaphore 2.0 documentation
site_author: Rendered Text
site_url: 'https://docs.semaphoreci.com'

# Repository
repo_name: semaphoreci/docs
repo_url: https://github.com/semaphoreci/docs

# Copyright
copyright: '&copy; 2009-2021 Rendered Text'

theme:
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  name: 'material'
  custom_dir: template
  logo: 'images/logo-white.svg'
  favicon: 'images/favicon.ico'
  feature:
    tabs: true
  palette:
    primary: 'green'
    accent: 'green'
extra_css:
  - 'stylesheets/extra.css'
extra_javascript:
  - 'javascript/extra.js'
extra:
  social:
    - type: 'github'
      link: 'https://github.com/semaphoreci'
    - type: 'twitter'
      link: 'https://twitter.com/semaphoreci'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/company/rendered-text'
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: '&#35;'
  - attr_list

nav:
  - Welcome: index.md
  - Guided Tour:
    - Getting started: guided-tour/getting-started.md
  - Essentials:
    - Concepts: essentials/concepts.md
    - Workflows and Pipelines: essentials/modeling-complex-workflows.md
    - Workflow triggers: essentials/project-workflow-trigger-options.md
    - Workflow scheduler/cron: essentials/schedule-a-workflow-run.md
    - "Fail-fast": essentials/fail-fast-stop-running-tests-on-the-first-failure.md
    - Deploying with promotions: essentials/deploying-with-promotions.md
    - Pipeline queues: essentials/pipeline-queues.md
    - Auto-cancel: essentials/auto-cancel-previous-pipelines-on-a-new-push.md
    - Skipping commits: essentials/skip-building-some-commits-with-ci-skip.md
    - Monorepo workflows: essentials/building-monorepo-projects.md
    - Tag-triggered deployment: essentials/tag-triggered-deployment.md
    - Job matrix: essentials/build-matrix.md
    - Prioritizing jobs: essentials/prioritization.md
    - Debugging with SSH: essentials/debugging-with-ssh-access.md
    - Caching: essentials/caching-dependencies-and-directories.md
    - Artifacts: essentials/artifacts.md
    - Setting environment variables: essentials/environment-variables.md
    - Secrets: essentials/using-secrets.md
    - Slack notifications: essentials/slack-notifications.md
    - Webhook notifications: essentials/webhook-notifications.md
    - GitHub status checks: essentials/configuring-github-status-checks.md
    - Status Badges: essentials/status-badges.md
    - Private dependencies: essentials/using-private-dependencies.md
    - Deployment dashboards: essentials/deployment-dashboards.md
    - Test Summary: essentials/test-summary.md
  - Programming Languages:
    - Android: programming-languages/android.md
    - C: programming-languages/c.md
    - C++: programming-languages/cpp.md
    - Clojure: programming-languages/clojure.md
    - Elixir: programming-languages/elixir.md
    - Erlang: programming-languages/erlang.md
    - Go: programming-languages/go.md
    - Java: programming-languages/java.md
    - JavaScript and Node.js: programming-languages/javascript-and-node-js.md
    - PHP: programming-languages/php.md
    - Python: programming-languages/python.md
    - Ruby: programming-languages/ruby.md
    - Rust: programming-languages/rust.md
    - Scala: programming-languages/scala.md
    - Swift: programming-languages/swift.md
  - CI/CD Environment:
    - Machine types: ci-cd-environment/machine-types.md
    - Choosing between a VM and Docker-based environment: ci-cd-environment/choosing-between-a-vm-and-docker-based-environment.md
    - Environment variables: ci-cd-environment/environment-variables.md
    - Linux VM:
      - Ubuntu 18.04 image: ci-cd-environment/ubuntu-18.04-image.md
      - Ubuntu 20.04 image: ci-cd-environment/ubuntu-20.04-image.md
      - Migrating to Ubuntu 20.04: ci-cd-environment/agent-migration-to-ubuntu2004.md
      - "Selecting language versions": ci-cd-environment/sem-version-managing-language-versions-on-linux.md
      - "Starting databases": ci-cd-environment/sem-service-managing-databases-and-services-on-linux.md
      - Configuring database access: ci-cd-environment/configuring-database-access.md
      - Nested virtualization: ci-cd-environment/nested-virtualization.md
    - Docker:
      - Docker-based CI/CD environment: ci-cd-environment/custom-ci-cd-environment-with-docker.md
      - Docker layer caching: ci-cd-environment/docker-layer-caching.md
      - Working with Docker: ci-cd-environment/working-with-docker.md
      - DockerHub authentication: ci-cd-environment/docker-authentication.md
      - Semaphore Container Registry: ci-cd-environment/semaphore-registry-images.md
    - "iOS/macOS":
      - macOS Xcode 11 image: ci-cd-environment/macos-xcode-11-image.md
      - macOS Xcode 12 image: ci-cd-environment/macos-xcode-12-image.md
    - Android:
      - Docker images: ci-cd-environment/android-images.md
      - Flutter example: ci-cd-environment/flutter.md
    - Self hosted agents:
      - Overview: ci-cd-environment/self-hosted-agents-overview.md
      - Creating a self hosted agent type: ci-cd-environment/creating-a-self-hosted-agent-type.md
      - Installing a self hosted agent: ci-cd-environment/installing-a-self-hosted-agent.md
      - Configuring a self hosted agent: ci-cd-environment/configuring-a-self-hosted-agent.md
  - Examples:
    - Tutorials and example projects: examples/tutorials-and-example-projects.md
    - Continuous Integration:
      - Rails continuous integration: examples/rails-continuous-integration.md
      - Node.js and TypeScript continuous integration: examples/node-js-and-typescript-continuous-integration.md
      - iOS continuous integration with Xcode: examples/ios-continuous-integration-with-xcode.md
      - CI/CD for microservices on Kubernetes: examples/ci-cd-for-microservices-on-kubernetes.md
      - Using Docker Compose in CI: examples/using-docker-compose-in-ci.md
      - Laravel PHP continuous integration: examples/laravel-php-continuous-integration.md
      - Django continuous integration: examples/django-continuous-integration.md
      - Java Spring continuous integration: examples/java-spring-continuous-integration.md
      - Download and cache a custom file: examples/download-and-cache-a-custom-file.md
      - Code signing for iOS projects: examples/code-signing-for-ios-projects.md
      - Golang continuous integration: examples/golang-continuous-integration.md
      - Elixir Phoenix continuous integration: examples/elixir-phoenix-continuous-integration.md
      - Scala Play continuous integration: examples/scala-play-continuous-integration.md
      - Configuring parallel tests with Code Climate: examples/configuring-parallel-tests-with-code-climate.md
      - Clojure Luminus CI/CD: examples/clojure-luminus-ci-cd.md
      - Change-based execution for monorepos: examples/change-based-execution-for-monorepos.md
      - Using Terraform with Google Cloud: examples/using-terraform-with-google-cloud.md
    - Deployment:
      - Zeit Now continuous deployment: examples/zeit-now-continuous-deployment.md
      - Publishing Docker images on DockerHub: examples/publishing-docker-images-on-dockerhub.md
      - Pushing Docker images to AWS Elastic Container Registry (ECR): examples/pushing-docker-images-to-aws-elastic-container-registry-ecr.md
      - Heroku deployment: examples/heroku-deployment.md
      - Continuous deployment of a static website: examples/continuous-deployment-of-a-static-website.md
      - Pushing Docker images to Google Container Registry (GCR): examples/pushing-docker-images-to-google-container-registry-gcr.md
      - Google Cloud run continuous deployment: examples/google-cloud-run-continuous-deployment.md
      - Deploy to DigitalOcean Kubernetes: examples/deploy-to-digitalocean.md
      - Netlify continuous deployment: examples/netlify-continuous-deployment.md
      - Deployment to AWS Elastic Beanstalk: examples/deployment-to-aws-elastic-beanstalk.md
      - HockeyApp iOS app distribution: examples/hockeyapp-ios-app-distribution.md
      - TestFlight iOS app distribution: examples/testflight-ios-app-distribution.md
  - Reference:
    - Pipeline YAML: reference/pipeline-yaml-reference.md
    - Conditions YAML: reference/conditions-reference.md
    - Secrets YAML: reference/secrets-yaml-reference.md
    - Projects YAML: reference/projects-yaml-reference.md
    - Dashboards YAML: reference/dashboards-yaml-reference.md
    - Jobs YAML: reference/jobs-yaml-reference.md
    - Notifications YAML: reference/notifications-yaml-reference.md
    - sem CLI: reference/sem-command-line-tool.md
    - artifact CLI: reference/artifact-cli-reference.md
    - test results CLI: reference/test-results-cli-reference.md
    - API: reference/api-v1alpha.md
    - Toolbox: reference/toolbox-reference.md
    - Quotas and limits: reference/quotas-and-limits.md
    - Semaphore Changelog: reference/semaphore-changelog.md
  - Account Management:
    - Organizations: account-management/organizations.md
    - Billing: account-management/billing.md
    - Plans: account-management/plans.md
    - Permission levels: account-management/permission-levels.md
    - Connecting your GitHub account and Semaphore: account-management/connecting-github-and-semaphore.md
    - Checking the connection between GitHub and Semaphore 2.0: account-management/checking-the-connection-between-github-and-semaphore-2.0.md
    - Discounts: account-management/discounts.md
    - Working with GitHub SSO: account-management/working-with-github-sso.md
  - FAQ:
    - FAQ: faq/faq.md
    - Managing projects: faq/managing-projects.md
    - Migration guide for Semaphore Classic users: faq/migration-guide-for-semaphore-classic-users.md
